[package]
name = "process-bonk"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
native-dialog = "0.7.0"

sysinfo = "0.30.5"
toml = "0.8.8"

