[package]
name = "process-bonk"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
native-dialog = "0.7.0"

sysinfo = "0.31.4"
toml = "0.8.19"
chrono = "0.4.38"

